apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-demo
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: app
          image: ghcr.io/your-org/argocd-demo:int
          env:
            - name: APP_ENV
              value: "int"
