apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-demo-test
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/your-org/argocd-k8s-demo'
    targetRevision: HEAD
    path: k8s/overlays/test
  destination:
    server: https://kubernetes.default.svc
    namespace: test
  syncPolicy:
    automated: {}
