name: CI Build & Push

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Maven
        run: mvn -DskipTests package --no-transfer-progress

      - name: Login to registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push images (latest + sha)
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/argocd-demo:latest
            ghcr.io/${{ github.repository_owner }}/argocd-demo:${{ github.sha }}
      # Update overlays to use immutable commit SHA tag (only on main)
      - name: Install yq (mikefarah)
        if: github.ref == 'refs/heads/main'
        run: |
          curl -sSL https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -o /usr/local/bin/yq
          chmod +x /usr/local/bin/yq

      - name: Update overlays with SHA image tag (yq)
        if: github.ref == 'refs/heads/main'
        env:
          NEW_TAG: ${{ github.sha }}
          REPO: ghcr.io/${{ github.repository_owner }}/argocd-demo
        run: |
          set -euo pipefail
          echo "Updating overlays to use image ${REPO}:${NEW_TAG}"
          for overlay in k8s/overlays/*; do
            file="$overlay/deployment-patch.yaml"
            if [ -f "$file" ]; then
              echo "Updating $file"
              # Use yq to set the image for the container named 'app'
              yq eval -i '.spec.template.spec.containers[] |= (select(.name == "app") | .image = env(REPO) + ":" + env(NEW_TAG))' "$file"
              git add "$file"
            fi
          done
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          if git diff --staged --quiet; then
            echo "No overlay changes"
          else
            git commit -m "ci: update kustomize overlays to image ${REPO}:${NEW_TAG}"
            git push origin HEAD:main
          fi
